<a href="https://colab.research.google.com/github/theashishreddy/ashi23/blob/master/numpy_p_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
result=np.add(arr,2)
print(result)
result=np.multiply(arr,2)

[3 4 5 6]


**Trigonametry**

In [ ]:
ang=np.array([1/4, 2/4])
b=np.cosh(ang)
print(ang)

[0.25 0.5 ]


# exponential

In [ ]:
result=np.exp(arr)
print(result)
result1=np.log(arr)
print(result1)

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


**Statistical**

In [ ]:
b=np.mean(arr)
c=np.std(arr)
print(arr)
print(b)
print(c)

[1 2 3 4]
2.5
1.118033988749895


**comparison**

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
conc=np.concatenate((a,b))
print(conc)

[1 2 3 4 5 6]


In [ ]:
res=np.greater(a,b)
print(res)
lesst=np.less(a,b)
print(lesst)


[False False False]
[ True  True  True]


# **broadcasting**


In [ ]:
print(arr)
broad=arr+2
print(broad)

[1 2 3 4]
[3 4 5 6]


# Array **Manipulation**


In [ ]:
#reshape
print(arr)
res=arr.reshape(2,2)
print(res)

[1 2 3 4]
[[1 2]
 [3 4]]


In [ ]:
#resize
d=np.array([1,2,3,4,5,6])
print(d)
d.resize(2,5)
print(d)

[1 2 3 4 5 6]
[[1 2 3 4 5]
 [6 0 0 0 0]]


In [ ]:
#Ravel
a=np.array([[1,2,3],[4,5,6]])
rav=a.ravel()
print(rav)
print(a)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


**Flatten**
same like ravel , but flatten does'nt modify original one


In [ ]:
'''a=[[1 2 3]
 [4 5 6]]'''
b=a.ravel()
b[0]=78
print(a)
# Flatten
c=a.flatten()
c[0]=90
print(a)

[[78  2  3]
 [ 4  5  6]]
[[78  2  3]
 [ 4  5  6]]


***squeeze***
remove axes of length one from array, remove dimensions

In [ ]:
d=np.array([[1,2,3,4,5,6]])
print(d.shape)
e=np.squeeze(d)
print(e)
print(e.shape)

(1, 6)
[1 2 3 4 5 6]
(6,)


**Expand dimensions**

In [ ]:
expand=np.expand_dims(e,axis=1)
print(expand)
print(expand.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


# **Splitting And joining**

In [ ]:
#1.split
arr=np.array([1,2,3,4,5,6])
newarr=np.split(arr,2)
print(newarr)


[array([1, 2, 3]), array([4, 5, 6])]


2) np.array_split

In [ ]:
asplit=np.array_split(arr,5)
print(asplit)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


3. horizontal and vertical split

In [ ]:
h=np.array([[1,2,3],[4,5,6]])
print(h)
hsplit=np.hsplit(h,3)
print(hsplit)
print("vertical split")
vsplit=np.vsplit(h,2)
print(vsplit)

[[1 2 3]
 [4 5 6]]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
vertical split
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [ ]:
print("horizontal combine")
hs=np.hstack((h,h))
print(hs)

print("vertical combine")
vs=np.vstack((h,h))
print(vs)

horizontal combine
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
vertical combine
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


# **Adding and removing Elements**

In [ ]:
g=np.array([1,2,3,4,5])
g = np.append(g,(6))
print(g)
np.insert(g,2,7)


[1 2 3 4 5 6]


array([1, 2, 7, 3, 4, 5, 6])

In [ ]:
#np.delete(g,2)
np.delete(g,[0,2])

array([2, 4, 5, 6])

In [ ]:
j=np.array([[1,2,3],[4,5,6],[7,8,9]])
resu=np.delete(j,2,axis=0)
print(resu)
res1=np.delete(j,2,axis=1)
print(res1)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]
 [7 8]]
